import type { NormalizedOpportunity } from "./types";

export const SEED_OPPORTUNITIES: NormalizedOpportunity[] = [
  {
    canonicalOcid: "ocds-seed-001",
    sourceName: "seed",
    sourceNoticeId: "SEED-001",
    sourceUrl: "https://example.com/notices/seed-001",
    submissionUrl: "https://example.com/submit/seed-001",
    title: "Digital Patient Communication Platform",
    description:
      "An NHS Trust is seeking a supplier to provide a secure digital patient communication platform, including SMS, email, appointment reminders, accessibility support, reporting, implementation, training, and ongoing support. The supplier must hold Cyber Essentials Plus and demonstrate NHS data handling compliance.",
    buyerName: "Example NHS Foundation Trust",
    buyerIdentifier: "GB-NHS-SEED-001",
    buyerRegion: "England",
    noticeType: "Contract Notice",
    procurementStage: "tender",
    status: "active",
    cpvCodes: ["72000000", "72212180", "64216000"],
    region: "North West England",
    valueAmount: 450000,
    valueCurrency: "GBP",
    publishedAt: "2026-06-01T09:00:00Z",
    updatedAt: "2026-06-01T09:00:00Z",
    deadlineAt: "2026-07-15T12:00:00Z",
    contractStartAt: "2026-09-01T00:00:00Z",
    contractEndAt: "2029-08-31T23:59:59Z",
    frameworkFlag: false,
    lots: [
      {
        id: "1",
        title: "Core platform and implementation",
        valueAmount: 450000,
        valueCurrency: "GBP",
        cpvCodes: ["72000000", "72212180"],
      },
    ],
    documents: [
      {
        id: "doc-1",
        title: "Invitation to Tender",
        documentType: "tenderDocument",
        url: "https://example.com/documents/seed-001-itt.pdf",
      },
    ],
    rawJson: {},
  },
  {
    canonicalOcid: "ocds-seed-002",
    sourceName: "seed",
    sourceNoticeId: "SEED-002",
    sourceUrl: "https://example.com/notices/seed-002",
    submissionUrl: "https://example.com/submit/seed-002",
    title: "Facilities Management and Cleaning Services",
    description:
      "A metropolitan borough council requires a supplier to provide integrated facilities management services including reactive and planned maintenance, statutory compliance, cleaning, grounds maintenance, and helpdesk services across a portfolio of civic buildings.",
    buyerName: "Example Metropolitan Borough Council",
    buyerIdentifier: "GB-LACO-SEED-002",
    buyerRegion: "England",
    noticeType: "Contract Notice",
    procurementStage: "tender",
    status: "active",
    cpvCodes: ["79993000", "90919200", "77310000"],
    region: "Yorkshire and the Humber",
    valueAmount: 2800000,
    valueCurrency: "GBP",
    publishedAt: "2026-05-20T09:00:00Z",
    updatedAt: "2026-05-20T09:00:00Z",
    deadlineAt: "2026-07-01T17:00:00Z",
    contractStartAt: "2027-01-01T00:00:00Z",
    contractEndAt: "2030-12-31T23:59:59Z",
    frameworkFlag: false,
    lots: [],
    documents: [],
    rawJson: {},
  },
  {
    canonicalOcid: "ocds-seed-003",
    sourceName: "seed",
    sourceNoticeId: "SEED-003",
    sourceUrl: "https://example.com/notices/seed-003",
    submissionUrl: "https://example.com/submit/seed-003",
    title: "Responsive Repairs and Maintenance Framework",
    description:
      "A registered housing association is establishing a four-year framework agreement for the provision of responsive repairs, void works, planned maintenance, and emergency callout services across a stock of approximately 8,500 properties.",
    buyerName: "Example Housing Association",
    buyerIdentifier: "GB-HA-SEED-003",
    buyerRegion: "England",
    noticeType: "Contract Notice",
    procurementStage: "tender",
    status: "active",
    cpvCodes: ["45259000", "50700000", "45261000"],
    region: "South East England",
    valueAmount: 12000000,
    valueCurrency: "GBP",
    publishedAt: "2026-05-15T09:00:00Z",
    updatedAt: "2026-05-15T09:00:00Z",
    deadlineAt: "2026-06-30T12:00:00Z",
    contractStartAt: "2026-10-01T00:00:00Z",
    contractEndAt: "2030-09-30T23:59:59Z",
    frameworkFlag: true,
    lots: [
      {
        id: "1",
        title: "Lot 1 — North region",
        valueAmount: 6000000,
        valueCurrency: "GBP",
      },
      {
        id: "2",
        title: "Lot 2 — South region",
        valueAmount: 6000000,
        valueCurrency: "GBP",
      },
    ],
    documents: [],
    rawJson: {},
  },
  {
    canonicalOcid: "ocds-seed-004",
    sourceName: "seed",
    sourceNoticeId: "SEED-004",
    sourceUrl: "https://example.com/notices/seed-004",
    submissionUrl: "https://example.com/submit/seed-004",
    title: "Cyber Security Managed Service",
    description:
      "A Russell Group university is seeking a managed cyber security service provider to deliver 24/7 SOC monitoring, incident response, vulnerability management, penetration testing, security awareness training, and strategic advisory services.",
    buyerName: "Example University",
    buyerIdentifier: "GB-UNIV-SEED-004",
    buyerRegion: "England",
    noticeType: "Contract Notice",
    procurementStage: "tender",
    status: "active",
    cpvCodes: ["72212180", "79711000", "72315000"],
    region: "East of England",
    valueAmount: 1200000,
    valueCurrency: "GBP",
    publishedAt: "2026-06-02T09:00:00Z",
    updatedAt: "2026-06-02T09:00:00Z",
    deadlineAt: "2026-07-18T17:00:00Z",
    contractStartAt: "2026-10-01T00:00:00Z",
    contractEndAt: "2029-09-30T23:59:59Z",
    frameworkFlag: false,
    lots: [],
    documents: [
      {
        id: "doc-1",
        title: "Specification",
        documentType: "tenderDocument",
        url: "https://example.com/documents/seed-004-spec.pdf",
      },
    ],
    rawJson: {},
  },
  {
    canonicalOcid: "ocds-seed-005",
    sourceName: "seed",
    sourceNoticeId: "SEED-005",
    sourceUrl: "https://example.com/notices/seed-005",
    submissionUrl: "https://example.com/submit/seed-005",
    title: "Research and Evaluation Consultancy Services",
    description:
      "The Department for Transport requires a multidisciplinary consultancy to design and deliver research, evaluation, and analytical studies to support policy development and programme delivery across transport infrastructure, active travel, and safety.",
    buyerName: "Department for Transport",
    buyerIdentifier: "GB-GOV-DFT",
    buyerRegion: "England",
    noticeType: "Contract Notice",
    procurementStage: "tender",
    status: "active",
    cpvCodes: ["73200000", "73110000", "79310000"],
    region: "London",
    valueAmount: 3500000,
    valueCurrency: "GBP",
    publishedAt: "2026-05-28T09:00:00Z",
    updatedAt: "2026-05-28T09:00:00Z",
    deadlineAt: "2026-07-10T12:00:00Z",
    contractStartAt: "2026-10-01T00:00:00Z",
    contractEndAt: "2029-09-30T23:59:59Z",
    frameworkFlag: false,
    lots: [],
    documents: [],
    rawJson: {},
  },
  {
    canonicalOcid: "ocds-seed-006",
    sourceName: "seed",
    sourceNoticeId: "SEED-006",
    sourceUrl: "https://example.com/notices/seed-006",
    submissionUrl: "https://example.com/submit/seed-006",
    title: "Adult Social Care Provider Framework",
    description:
      "A county council is establishing a framework agreement for the provision of regulated residential care, nursing care, and supported living services for adults with physical disabilities, learning disabilities, mental health needs, and dementia.",
    buyerName: "Example County Council",
    buyerIdentifier: "GB-LACO-SEED-006",
    buyerRegion: "England",
    noticeType: "Contract Notice",
    procurementStage: "tender",
    status: "active",
    cpvCodes: ["85312000", "85311200", "85321000"],
    region: "South West England",
    valueAmount: 45000000,
    valueCurrency: "GBP",
    publishedAt: "2026-05-10T09:00:00Z",
    updatedAt: "2026-05-10T09:00:00Z",
    deadlineAt: "2026-06-28T12:00:00Z",
    contractStartAt: "2027-04-01T00:00:00Z",
    contractEndAt: "2031-03-31T23:59:59Z",
    frameworkFlag: true,
    lots: [],
    documents: [],
    rawJson: {},
  },
  {
    canonicalOcid: "ocds-seed-007",
    sourceName: "seed",
    sourceNoticeId: "SEED-007",
    sourceUrl: "https://example.com/notices/seed-007",
    submissionUrl: "https://example.com/submit/seed-007",
    title: "Victim Support and Advocacy Services",
    description:
      "A Police and Crime Commissioner is commissioning services to support victims of crime, domestic abuse, and sexual violence, including a 24/7 helpline, independent advocacy, therapeutic support, and community outreach in both urban and rural areas.",
    buyerName: "Example Police and Crime Commissioner",
    buyerIdentifier: "GB-PCC-SEED-007",
    buyerRegion: "England",
    noticeType: "Contract Notice",
    procurementStage: "tender",
    status: "active",
    cpvCodes: ["85000000", "85312300", "85311100"],
    region: "East Midlands",
    valueAmount: 2200000,
    valueCurrency: "GBP",
    publishedAt: "2026-06-03T09:00:00Z",
    updatedAt: "2026-06-03T09:00:00Z",
    deadlineAt: "2026-07-22T17:00:00Z",
    contractStartAt: "2027-01-01T00:00:00Z",
    contractEndAt: "2030-12-31T23:59:59Z",
    frameworkFlag: false,
    lots: [],
    documents: [],
    rawJson: {},
  },
  {
    canonicalOcid: "ocds-seed-008",
    sourceName: "seed",
    sourceNoticeId: "SEED-008",
    sourceUrl: "https://example.com/notices/seed-008",
    submissionUrl: "https://example.com/submit/seed-008",
    title: "Website Redesign, Hosting, and Ongoing Support",
    description:
      "A combined authority is seeking a digital agency to redesign and rebuild its public-facing website and intranet, provide reliable cloud hosting, ongoing accessibility compliance, content migration, and a two-year support contract.",
    buyerName: "Example Combined Authority",
    buyerIdentifier: "GB-CA-SEED-008",
    buyerRegion: "England",
    noticeType: "Contract Notice",
    procurementStage: "tender",
    status: "active",
    cpvCodes: ["72413000", "72415000", "72212000"],
    region: "West Midlands",
    valueAmount: 320000,
    valueCurrency: "GBP",
    publishedAt: "2026-06-04T09:00:00Z",
    updatedAt: "2026-06-04T09:00:00Z",
    deadlineAt: "2026-07-25T12:00:00Z",
    contractStartAt: "2026-10-01T00:00:00Z",
    contractEndAt: "2028-09-30T23:59:59Z",
    frameworkFlag: false,
    lots: [],
    documents: [],
    rawJson: {},
  },
  {
    canonicalOcid: "ocds-seed-009",
    sourceName: "seed",
    sourceNoticeId: "SEED-009",
    sourceUrl: "https://example.com/notices/seed-009",
    submissionUrl: "https://example.com/submit/seed-009",
    title: "Waste Collection Fleet Maintenance",
    description:
      "A borough council requires a specialist contractor to deliver scheduled preventative maintenance, reactive repairs, MOT preparation, body repairs, and emergency breakdown cover for a fleet of 38 refuse collection vehicles and 12 street cleansing vehicles.",
    buyerName: "Example Borough Council",
    buyerIdentifier: "GB-LACO-SEED-009",
    buyerRegion: "England",
    noticeType: "Contract Notice",
    procurementStage: "tender",
    status: "active",
    cpvCodes: ["50100000", "50114000", "50116000"],
    region: "South East England",
    valueAmount: 960000,
    valueCurrency: "GBP",
    publishedAt: "2026-05-22T09:00:00Z",
    updatedAt: "2026-05-22T09:00:00Z",
    deadlineAt: "2026-07-04T12:00:00Z",
    contractStartAt: "2026-10-01T00:00:00Z",
    contractEndAt: "2029-09-30T23:59:59Z",
    frameworkFlag: false,
    lots: [],
    documents: [],
    rawJson: {},
  },
  {
    canonicalOcid: "ocds-seed-010",
    sourceName: "seed",
    sourceNoticeId: "SEED-010",
    sourceUrl: "https://example.com/notices/seed-010",
    submissionUrl: "https://example.com/submit/seed-010",
    title: "IT Managed Services Framework — Multi-Academy Trust",
    description:
      "A multi-academy trust operating 14 schools seeks a supplier to provide a comprehensive IT managed service including device management, network infrastructure, cybersecurity, service desk, and strategic IT consultancy under a three-year framework.",
    buyerName: "Example Multi-Academy Trust",
    buyerIdentifier: "GB-EDU-SEED-010",
    buyerRegion: "England",
    noticeType: "Contract Notice",
    procurementStage: "tender",
    status: "active",
    cpvCodes: ["72000000", "72253200", "30213000"],
    region: "North East England",
    valueAmount: 1800000,
    valueCurrency: "GBP",
    publishedAt: "2026-05-30T09:00:00Z",
    updatedAt: "2026-05-30T09:00:00Z",
    deadlineAt: "2026-07-11T17:00:00Z",
    contractStartAt: "2026-09-01T00:00:00Z",
    contractEndAt: "2029-08-31T23:59:59Z",
    frameworkFlag: true,
    lots: [],
    documents: [
      {
        id: "doc-1",
        title: "Specification and Requirements",
        documentType: "tenderDocument",
        url: "https://example.com/documents/seed-010-spec.pdf",
      },
    ],
    rawJson: {},
  },
];
